// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package orderservice

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"github.com/talense-tasks/backend-trainee-assignment-autumn-2026-markgredasov-5b2b61ca/internal/model/menu"
	"github.com/talense-tasks/backend-trainee-assignment-autumn-2026-markgredasov-5b2b61ca/internal/model/order"
	"github.com/talense-tasks/backend-trainee-assignment-autumn-2026-markgredasov-5b2b61ca/internal/model/restaurant"
	"github.com/talense-tasks/backend-trainee-assignment-autumn-2026-markgredasov-5b2b61ca/internal/service/webhook"
)

// NewMockRestaurantRepository creates a new instance of MockRestaurantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestaurantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestaurantRepository {
	mock := &MockRestaurantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestaurantRepository is an autogenerated mock type for the RestaurantRepository type
type MockRestaurantRepository struct {
	mock.Mock
}

type MockRestaurantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestaurantRepository) EXPECT() *MockRestaurantRepository_Expecter {
	return &MockRestaurantRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockRestaurantRepository
func (_mock *MockRestaurantRepository) GetByID(ctx context.Context, id string) (restaurant.Restaurant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 restaurant.Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (restaurant.Restaurant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) restaurant.Restaurant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(restaurant.Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurantRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRestaurantRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRestaurantRepository_Expecter) GetByID(ctx any, id any) *MockRestaurantRepository_GetByID_Call {
	return &MockRestaurantRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRestaurantRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestaurantRepository_GetByID_Call) Return(restaurant1 restaurant.Restaurant, err error) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Return(restaurant1, err)
	return _c
}

func (_c *MockRestaurantRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (restaurant.Restaurant, error)) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// GetManyByIDs provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) GetManyByIDs(ctx context.Context, ids []uuid.UUID) ([]menu.MenuItem, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetManyByIDs")
	}

	var r0 []menu.MenuItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]menu.MenuItem, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []menu.MenuItem); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]menu.MenuItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_GetManyByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManyByIDs'
type MockMenuRepository_GetManyByIDs_Call struct {
	*mock.Call
}

// GetManyByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockMenuRepository_Expecter) GetManyByIDs(ctx any, ids any) *MockMenuRepository_GetManyByIDs_Call {
	return &MockMenuRepository_GetManyByIDs_Call{Call: _e.mock.On("GetManyByIDs", ctx, ids)}
}

func (_c *MockMenuRepository_GetManyByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockMenuRepository_GetManyByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMenuRepository_GetManyByIDs_Call) Return(menuItems []menu.MenuItem, err error) *MockMenuRepository_GetManyByIDs_Call {
	_c.Call.Return(menuItems, err)
	return _c
}

func (_c *MockMenuRepository_GetManyByIDs_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) ([]menu.MenuItem, error)) *MockMenuRepository_GetManyByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, o order.Order) error {
	ret := _mock.Called(ctx, o)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, order.Order) error); ok {
		r0 = returnFunc(ctx, o)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - o order.Order
func (_e *MockOrderRepository_Expecter) Create(ctx any, o any) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, o)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, o order.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 order.Order
		if args[1] != nil {
			arg1 = args[1].(order.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, o order.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetByID(ctx context.Context, id uuid.UUID) (order.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) order.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(order.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderRepository_Expecter) GetByID(ctx any, id any) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(order1 order.Order, err error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (order.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByRestaurant provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) ListActiveByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]order.Order, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByRestaurant")
	}

	var r0 []order.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]order.Order, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []order.Order); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]order.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_ListActiveByRestaurant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByRestaurant'
type MockOrderRepository_ListActiveByRestaurant_Call struct {
	*mock.Call
}

// ListActiveByRestaurant is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
func (_e *MockOrderRepository_Expecter) ListActiveByRestaurant(ctx any, restaurantID any) *MockOrderRepository_ListActiveByRestaurant_Call {
	return &MockOrderRepository_ListActiveByRestaurant_Call{Call: _e.mock.On("ListActiveByRestaurant", ctx, restaurantID)}
}

func (_c *MockOrderRepository_ListActiveByRestaurant_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID)) *MockOrderRepository_ListActiveByRestaurant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_ListActiveByRestaurant_Call) Return(orders []order.Order, err error) *MockOrderRepository_ListActiveByRestaurant_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_ListActiveByRestaurant_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID) ([]order.Order, error)) *MockOrderRepository_ListActiveByRestaurant_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateStatus(ctx context.Context, id uuid.UUID, from order.Status, to order.Status) error {
	ret := _mock.Called(ctx, id, from, to)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, order.Status, order.Status) error); ok {
		r0 = returnFunc(ctx, id, from, to)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - from order.Status
//   - to order.Status
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx any, id any, from any, to any) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, from, to)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, from order.Status, to order.Status)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 order.Status
		if args[2] != nil {
			arg2 = args[2].(order.Status)
		}
		var arg3 order.Status
		if args[3] != nil {
			arg3 = args[3].(order.Status)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(err error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, from order.Status, to order.Status) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockTxManager
func (_mock *MockTxManager) WithTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTxManager_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTxManager_Expecter) WithTx(ctx any, fn any) *MockTxManager_WithTx_Call {
	return &MockTxManager_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockTxManager_WithTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTxManager_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_WithTx_Call) Return(err error) *MockTxManager_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTxManager_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebhookSender creates a new instance of MockWebhookSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebhookSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebhookSender {
	mock := &MockWebhookSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebhookSender is an autogenerated mock type for the WebhookSender type
type MockWebhookSender struct {
	mock.Mock
}

type MockWebhookSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebhookSender) EXPECT() *MockWebhookSender_Expecter {
	return &MockWebhookSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockWebhookSender
func (_mock *MockWebhookSender) Send(ctx context.Context, webhookURL string, payload webhook.OrderPayload) error {
	ret := _mock.Called(ctx, webhookURL, payload)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, webhook.OrderPayload) error); ok {
		r0 = returnFunc(ctx, webhookURL, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebhookSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockWebhookSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - webhookURL string
//   - payload webhook.OrderPayload
func (_e *MockWebhookSender_Expecter) Send(ctx any, webhookURL any, payload any) *MockWebhookSender_Send_Call {
	return &MockWebhookSender_Send_Call{Call: _e.mock.On("Send", ctx, webhookURL, payload)}
}

func (_c *MockWebhookSender_Send_Call) Run(run func(ctx context.Context, webhookURL string, payload webhook.OrderPayload)) *MockWebhookSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 webhook.OrderPayload
		if args[2] != nil {
			arg2 = args[2].(webhook.OrderPayload)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebhookSender_Send_Call) Return(err error) *MockWebhookSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebhookSender_Send_Call) RunAndReturn(run func(ctx context.Context, webhookURL string, payload webhook.OrderPayload) error) *MockWebhookSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
