// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package catalogservice

import (
	"context"

	"github.com/google/uuid"
	"github.com/markgredasov/food-delivery-mvp/internal/model/menu"
	"github.com/markgredasov/food-delivery-mvp/internal/model/restaurant"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRestaurantRepository creates a new instance of MockRestaurantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestaurantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestaurantRepository {
	mock := &MockRestaurantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestaurantRepository is an autogenerated mock type for the RestaurantRepository type
type MockRestaurantRepository struct {
	mock.Mock
}

type MockRestaurantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestaurantRepository) EXPECT() *MockRestaurantRepository_Expecter {
	return &MockRestaurantRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockRestaurantRepository
func (_mock *MockRestaurantRepository) GetByID(ctx context.Context, restaurantID string) (restaurant.Restaurant, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 restaurant.Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (restaurant.Restaurant, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) restaurant.Restaurant); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		r0 = ret.Get(0).(restaurant.Restaurant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurantRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRestaurantRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID string
func (_e *MockRestaurantRepository_Expecter) GetByID(ctx any, restaurantID any) *MockRestaurantRepository_GetByID_Call {
	return &MockRestaurantRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, restaurantID)}
}

func (_c *MockRestaurantRepository_GetByID_Call) Run(run func(ctx context.Context, restaurantID string)) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestaurantRepository_GetByID_Call) Return(restaurant1 restaurant.Restaurant, err error) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Return(restaurant1, err)
	return _c
}

func (_c *MockRestaurantRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, restaurantID string) (restaurant.Restaurant, error)) *MockRestaurantRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function for the type MockRestaurantRepository
func (_mock *MockRestaurantRepository) ListActive(ctx context.Context) ([]restaurant.Restaurant, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []restaurant.Restaurant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]restaurant.Restaurant, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []restaurant.Restaurant); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]restaurant.Restaurant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRestaurantRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockRestaurantRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRestaurantRepository_Expecter) ListActive(ctx any) *MockRestaurantRepository_ListActive_Call {
	return &MockRestaurantRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MockRestaurantRepository_ListActive_Call) Run(run func(ctx context.Context)) *MockRestaurantRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRestaurantRepository_ListActive_Call) Return(restaurants []restaurant.Restaurant, err error) *MockRestaurantRepository_ListActive_Call {
	_c.Call.Return(restaurants, err)
	return _c
}

func (_c *MockRestaurantRepository_ListActive_Call) RunAndReturn(run func(ctx context.Context) ([]restaurant.Restaurant, error)) *MockRestaurantRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMenuRepository creates a new instance of MockMenuRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMenuRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMenuRepository {
	mock := &MockMenuRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMenuRepository is an autogenerated mock type for the MenuRepository type
type MockMenuRepository struct {
	mock.Mock
}

type MockMenuRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMenuRepository) EXPECT() *MockMenuRepository_Expecter {
	return &MockMenuRepository_Expecter{mock: &_m.Mock}
}

// ListByRestaurantID provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) ListByRestaurantID(ctx context.Context, restaurantID string) ([]menu.MenuItem, error) {
	ret := _mock.Called(ctx, restaurantID)

	if len(ret) == 0 {
		panic("no return value specified for ListByRestaurantID")
	}

	var r0 []menu.MenuItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]menu.MenuItem, error)); ok {
		return returnFunc(ctx, restaurantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []menu.MenuItem); ok {
		r0 = returnFunc(ctx, restaurantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]menu.MenuItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, restaurantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_ListByRestaurantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRestaurantID'
type MockMenuRepository_ListByRestaurantID_Call struct {
	*mock.Call
}

// ListByRestaurantID is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID string
func (_e *MockMenuRepository_Expecter) ListByRestaurantID(ctx any, restaurantID any) *MockMenuRepository_ListByRestaurantID_Call {
	return &MockMenuRepository_ListByRestaurantID_Call{Call: _e.mock.On("ListByRestaurantID", ctx, restaurantID)}
}

func (_c *MockMenuRepository_ListByRestaurantID_Call) Run(run func(ctx context.Context, restaurantID string)) *MockMenuRepository_ListByRestaurantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMenuRepository_ListByRestaurantID_Call) Return(menuItems []menu.MenuItem, err error) *MockMenuRepository_ListByRestaurantID_Call {
	_c.Call.Return(menuItems, err)
	return _c
}

func (_c *MockMenuRepository_ListByRestaurantID_Call) RunAndReturn(run func(ctx context.Context, restaurantID string) ([]menu.MenuItem, error)) *MockMenuRepository_ListByRestaurantID_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceMenu provides a mock function for the type MockMenuRepository
func (_mock *MockMenuRepository) ReplaceMenu(ctx context.Context, restaurantID uuid.UUID, items []menu.MenuItem) ([]menu.MenuItem, error) {
	ret := _mock.Called(ctx, restaurantID, items)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceMenu")
	}

	var r0 []menu.MenuItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []menu.MenuItem) ([]menu.MenuItem, error)); ok {
		return returnFunc(ctx, restaurantID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []menu.MenuItem) []menu.MenuItem); ok {
		r0 = returnFunc(ctx, restaurantID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]menu.MenuItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []menu.MenuItem) error); ok {
		r1 = returnFunc(ctx, restaurantID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMenuRepository_ReplaceMenu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceMenu'
type MockMenuRepository_ReplaceMenu_Call struct {
	*mock.Call
}

// ReplaceMenu is a helper method to define mock.On call
//   - ctx context.Context
//   - restaurantID uuid.UUID
//   - items []menu.MenuItem
func (_e *MockMenuRepository_Expecter) ReplaceMenu(ctx any, restaurantID any, items any) *MockMenuRepository_ReplaceMenu_Call {
	return &MockMenuRepository_ReplaceMenu_Call{Call: _e.mock.On("ReplaceMenu", ctx, restaurantID, items)}
}

func (_c *MockMenuRepository_ReplaceMenu_Call) Run(run func(ctx context.Context, restaurantID uuid.UUID, items []menu.MenuItem)) *MockMenuRepository_ReplaceMenu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []menu.MenuItem
		if args[2] != nil {
			arg2 = args[2].([]menu.MenuItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMenuRepository_ReplaceMenu_Call) Return(menuItems []menu.MenuItem, err error) *MockMenuRepository_ReplaceMenu_Call {
	_c.Call.Return(menuItems, err)
	return _c
}

func (_c *MockMenuRepository_ReplaceMenu_Call) RunAndReturn(run func(ctx context.Context, restaurantID uuid.UUID, items []menu.MenuItem) ([]menu.MenuItem, error)) *MockMenuRepository_ReplaceMenu_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) List(ctx context.Context) ([]menu.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []menu.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]menu.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []menu.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]menu.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryRepository_Expecter) List(ctx any) *MockCategoryRepository_List_Call {
	return &MockCategoryRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockCategoryRepository_List_Call) Run(run func(ctx context.Context)) *MockCategoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_List_Call) Return(categorys []menu.Category, err error) *MockCategoryRepository_List_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]menu.Category, error)) *MockCategoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockTxManager
func (_mock *MockTxManager) WithTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTxManager_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTxManager_Expecter) WithTx(ctx any, fn any) *MockTxManager_WithTx_Call {
	return &MockTxManager_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockTxManager_WithTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTxManager_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_WithTx_Call) Return(err error) *MockTxManager_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTxManager_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
